# Generated by Django 5.0.6 on 2024-06-10 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatoAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=100, verbose_name='Nombre del plato')),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Alimentos_Santiago/media/platos/', verbose_name='Imagen del plato')),
            ],
            options={
                'verbose_name': 'Plato Admin',
                'verbose_name_plural': 'Platos Admin',
                'ordering': ['nombre_plato', 'precio', 'disponibilidad'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre proveedor')),
                ('pais', models.CharField(max_length=25, verbose_name='País')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha de contrato')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('especialidad_tipo_plato', models.CharField(max_length=25, verbose_name='Especialidad tipo de plato')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Repartidores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Repartidor')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha de contrato')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlatoProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=100, verbose_name='Nombre del plato')),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Alimentos_Santiago/media/platos/', verbose_name='Imagen del plato')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alimentos_Santiago.proveedor')),
            ],
            options={
                'verbose_name': 'Plato Proveedor',
                'verbose_name_plural': 'Platos Proveedores',
                'ordering': ['proveedor', 'nombre_plato'],
            },
        ),
        migrations.CreateModel(
            name='DestinoRepartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField(verbose_name='Fecha Despacho')),
                ('hora', models.TimeField(default='00:00:00', verbose_name='Hora Despacho')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alimentos_Santiago.repartidores')),
            ],
            options={
                'verbose_name': 'Destino Repartidor',
                'verbose_name_plural': 'Destinos Repartidores',
                'ordering': ['fecha_despacho'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaPlatoProveedor',
            fields=[
                ('plato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Alimentos_Santiago.platoproveedor')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio oferta')),
                ('disponible', models.BooleanField(default=False, verbose_name='Disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Alimentos_Santiago/media/ofertas/', verbose_name='Imagen de la oferta')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='Alimentos_Santiago.proveedor')),
            ],
            options={
                'verbose_name': 'Oferta de plato proveedor',
                'verbose_name_plural': 'Ofertas de platos proveedores',
                'ordering': ['proveedor', 'plato'],
            },
        ),
    ]
