# Generated by Django 5.0.6 on 2024-06-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinorepartidor',
            old_name='hora',
            new_name='hora_despacho',
        ),
    ]
