# Generated by Django 5.0.6 on 2024-06-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_despacho', models.CharField(max_length=50)),
                ('fecha_compra', models.DateTimeField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alimentos_Santiago.platoproveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alimentos_Santiago.userprofile')),
            ],
        ),
    ]
