# Generated by Django 5.0.6 on 2024-06-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0002_detallecompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='usuario',
        ),
    ]
