# Generated by Django 5.0.6 on 2024-06-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0002_proveedor_platoproveedor_ofertaplatoproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatoAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=100, verbose_name='Nombre del plato')),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Alimentos_Santiago/media/platos/', verbose_name='Imagen del plato')),
            ],
            options={
                'verbose_name': 'Plato Admin',
                'verbose_name_plural': 'Platos Admin',
                'ordering': ['nombre_plato', 'precio', 'disponibilidad'],
            },
        ),
        migrations.CreateModel(
            name='Repartidores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Repartidor')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha de contrato')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField(verbose_name='Fecha Despacho')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alimentos_Santiago.repartidores')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['fecha_despacho'],
            },
        ),
    ]
