# Generated by Django 5.0.6 on 2024-06-11 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0002_rename_hora_destinorepartidor_hora_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertaplatoproveedor',
            name='plato',
        ),
        migrations.RemoveField(
            model_name='ofertaplatoproveedor',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='PlatoAdmin',
        ),
        migrations.DeleteModel(
            name='OfertaPlatoProveedor',
        ),
    ]
