# Generated by Django 5.0.6 on 2024-06-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0003_platoadmin_repartidores_destino'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destino',
            new_name='DestinoRepartidor',
        ),
    ]
