# Generated by Django 5.0.6 on 2024-06-13 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0004_remove_destinorepartidor_plato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField(verbose_name='Fecha Despacho')),
                ('hora_despacho', models.TimeField(default='00:00:00', verbose_name='Hora Despacho')),
                ('tipo_despacho', models.CharField(choices=[('TIENDA', 'En tienda'), ('DELIVERY', 'Delivery')], max_length=25, verbose_name='Tipo de despacho')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('plato', models.ManyToManyField(to='Alimentos_Santiago.platoproveedor')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alimentos_Santiago.repartidores')),
            ],
            options={
                'verbose_name': 'Destino Repartidor',
                'verbose_name_plural': 'Destinos Repartidores',
                'ordering': ['fecha_despacho'],
            },
        ),
        migrations.DeleteModel(
            name='DestinoRepartidor',
        ),
    ]
