# Generated by Django 5.0.6 on 2024-06-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0004_detallecompra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
