# Generated by Django 5.0.6 on 2024-06-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0005_detallepedido_delete_destinorepartidor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='tipo_despacho',
            new_name='retiro',
        ),
    ]
