# Generated by Django 5.0.6 on 2024-06-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0007_alter_detallepedido_retiro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
