# Generated by Django 5.0.6 on 2024-06-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alimentos_Santiago', '0008_delete_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='platos_disponibles',
            field=models.ManyToManyField(related_name='plato_empresa', to='Alimentos_Santiago.platoproveedor'),
        ),
    ]
